<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>bundleUUID</key>
	<string>E3BADC20-6B0E-11D9-9DC9-000D93589AF7</string>
	<key>firstLineMatch</key>
	<string>^#!/.*\bpython[0-9.-]*\b</string>
	<key>foldingStartMarker</key>
	<string>^\s*(def|class)\s+([.a-zA-Z0-9_ &lt;]+)\s*(\((.*)\))?\s*:|\{\s*$|\(\s*$|\[\s*$|^\s*"""(?=.)(?!.*""")</string>
	<key>foldingStopMarker</key>
	<string>^\s*$|^\s*\}|^\s*\]|^\s*\)|^\s*"""\s*$</string>
	<key>name</key>
	<string>Python (PyTags)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\b(?=from\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.from.python</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.python.pytags.import</string>
			<key>end</key>
			<string>(?&lt;!\\)(?=\n)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(from)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.import.python</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.python.pytags.import.module</string>
					<key>end</key>
					<string>\b(?=import\b)|((?&lt;!\\)(?=\n))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.missing-section-begin.python</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(import)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.import.python</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.python.pytags.import.member</string>
					<key>end</key>
					<string>(?&lt;!\\)(?=\n)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\bas\b</string>
							<key>name</key>
							<string>keyword.other.python</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(import)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.python</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.python.pytags.import.module</string>
			<key>end</key>
			<string>(?&lt;!\\)\n</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bas\b</string>
					<key>name</key>
					<string>keyword.other.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.python</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.python.pytags</string>
	<key>uuid</key>
	<string>F23DB5B2-7D08-11D9-A709-000D93B6E43D</string>
</dict>
</plist>
